version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/deliverable-4/app

    steps:
      - checkout
      - run: cd deliverable-4/app && npm install
      - run: cd deliverable-4/app && npm test
      - run: cd deliverable-4/app && npm run-script build
      - run: cd deliverable-4/app && npm run-script netlify:deploy
